### PR TITLE
Adding schematic

### PR DESCRIPTION
**Pull request by MellieZito**

### CODE REVIEW

**Comment by ljordan51** [comment]
@coreyacl is it weird that there are changes to the template schematic here? doesn't seem right to me

**Comment by ljordan51** [comment]
ya @coreyacl actually there were edits to the symbols table and also the pcb
and the schematic was just deleted
I think we need to figure out where/when these changes happened and revert them
@MellieZito I'll message you on slack to arrange a time to do this

**Comment by ljordan51** [comment]
wait now I'm extra confused, the alst three commits are from you @coreyacl deleting all the template files but somehow in the pull request only the schematic file was deleted, the other two just have some changes

**Comment by coreyacl** [comment]
modifed and fixed some things on my side.

**Pull request closed without merging**
